name: Auto Update Playlist

on:
  schedule:
    - cron: "0 */6 * * *"  # ყოველ 6 საათში ერთხელ
  workflow_dispatch:      # ხელით გასაშვები ღილაკი

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run update script
        run: python update_playlist.py

      - name: Commit and push changes
        run: |
          git config --global user.name "vardzelashvildima08-bot"
          git config --global user.email "bot@example.com"
          git add playlist.m3u
          git commit -m "Auto update playlist"
          git push
